### PR TITLE
Pin ml5 version to 0.5.0 to avoid errors

### PR DESCRIPTION
**Pull request by karel1980**
solves #14

### CODE REVIEW

**Comment by VeerpalBrar** [comment]
Hi, thanks for fixing this issue! I'll do a quick test on my machine sometime this week before approving.

**Review by VeerpalBrar — APPROVED** [review]
Tested this today and can  confirm the error happened to me on master and was gone after switching to this branch. I also double checked that the ml5 version was 0.5.0 and the purple boxes appeared. 

👍🏼

**Comment by mahikap** [comment]
Thank you Karel, how did you realize the issue was from the ml5 version? 
Also thanks for the side note about initializing AudioContext after the user interacts. Will look into it and fix it :)

**Comment by karel1980** [comment]
I guessed it was related to ml5 from the stack trace, and then I tried
downgrading until the error went away.

**Pull request merged**
